#Puerto API
server:
  port: 8082
#DB
spring:
  data:
    mongodb:
      port: 27017
      auto-index-creation: 'true'
      database: customerdb
      host: mongodb
  application:
    name: ms-customer
#Cliente Eureka
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always                         