server:
  port: 8082

spring:
  data:
    mongodb:
      port: 27019
      auto-index-creation: 'true'
      database: customerdb
      host: localhost
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka                     