#Puerto API
server:
  port: 8083
#DB
spring:
  data:
    mongodb:
      port: 27017
      auto-index-creation: 'true'
      database: creditdb
      host: mongodb
  application:
    name: ms-credit
  config:
    import: optional:http://config-server:8888/
#Cliente Eureka
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always                                         