#Puerto API
server:
  port: 8090
#Cliente Eureka      
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always      
#Gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-customer
          uri: http://ms-customer:8082/
          predicates:
            - Path=/api/customer/**
        - id: ms-account
          uri: http://ms-account:8081/
          predicates:
            - Path=/api/account/**
        - id: ms-credit
          uri: http://ms-credit:8083/
          predicates:
            - Path=/api/credits/**                           